//
// Generated file, do not edit! Created by nedtool 5.6 from application/base/ApplicationPacketNdp.msg.
//

#ifndef __INET_APPLICATIONPACKETNDP_M_H
#define __INET_APPLICATIONPACKETNDP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

/**
 * Class generated from <tt>application/base/ApplicationPacketNdp.msg:9</tt> by nedtool.
 * <pre>
 * //
 * // Generic application packet
 * //
 * packet ApplicationPacketNdp
 * {
 *     long sequenceNumber;
 * }
 * </pre>
 */
class ApplicationPacketNdp : public ::omnetpp::cPacket
{
  protected:
    long sequenceNumber;

  private:
    void copy(const ApplicationPacketNdp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplicationPacketNdp&);

  public:
    ApplicationPacketNdp(const char *name=nullptr, short kind=0);
    ApplicationPacketNdp(const ApplicationPacketNdp& other);
    virtual ~ApplicationPacketNdp();
    ApplicationPacketNdp& operator=(const ApplicationPacketNdp& other);
    virtual ApplicationPacketNdp *dup() const override {return new ApplicationPacketNdp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual long getSequenceNumber() const;
    virtual void setSequenceNumber(long sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationPacketNdp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationPacketNdp& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_APPLICATIONPACKETNDP_M_H

