//
// Generated file, do not edit! Created by nedtool 5.6 from application/ndpapp/GenericAppMsgNdp.msg.
//

#ifndef __INET_GENERICAPPMSGNDP_M_H
#define __INET_GENERICAPPMSGNDP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/common/INETDefs.h"
// }}


namespace inet {

/**
 * Class generated from <tt>application/ndpapp/GenericAppMsgNdp.msg:11</tt> by nedtool.
 * <pre>
 * packet GenericAppMsgNdp
 * {
 *     int numPaketToSend;  //  if this is a reader(receiver)
 *     bool isSender;  // receiver 
 *     bool isReceiver;  // receiver 
 *     bool isLongFlow;
 *     bool serverClose;        // if true, server should close the
 * }
 * </pre>
 */
class GenericAppMsgNdp : public ::omnetpp::cPacket
{
  protected:
    int numPaketToSend;
    bool isSender;
    bool isReceiver;
    bool isLongFlow;
    bool serverClose;

  private:
    void copy(const GenericAppMsgNdp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericAppMsgNdp&);

  public:
    GenericAppMsgNdp(const char *name=nullptr, short kind=0);
    GenericAppMsgNdp(const GenericAppMsgNdp& other);
    virtual ~GenericAppMsgNdp();
    GenericAppMsgNdp& operator=(const GenericAppMsgNdp& other);
    virtual GenericAppMsgNdp *dup() const override {return new GenericAppMsgNdp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNumPaketToSend() const;
    virtual void setNumPaketToSend(int numPaketToSend);
    virtual bool getIsSender() const;
    virtual void setIsSender(bool isSender);
    virtual bool getIsReceiver() const;
    virtual void setIsReceiver(bool isReceiver);
    virtual bool getIsLongFlow() const;
    virtual void setIsLongFlow(bool isLongFlow);
    virtual bool getServerClose() const;
    virtual void setServerClose(bool serverClose);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GenericAppMsgNdp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GenericAppMsgNdp& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_GENERICAPPMSGNDP_M_H

