//
// Generated file, do not edit! Created by nedtool 5.6 from application/ndpapp/GenericAppMsgNdp.msg.
//

#ifndef __INET_GENERICAPPMSGNDP_M_H
#define __INET_GENERICAPPMSGNDP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class GenericAppMsgNdp;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>application/ndpapp/GenericAppMsgNdp.msg:11</tt> by nedtool.
 * <pre>
 * class GenericAppMsgNdp extends FieldsChunk
 * {
 *     int numPacketsToSend;  //  if this is a reader(receiver)
 *     bool isSender;  // receiver 
 *     bool isReceiver;  // receiver 
 *     bool isLongFlow;
 *     bool serverClose;        // if true, server should close the
 *     uint32_t sequenceNumber; //new TODO
 * }
 * </pre>
 */
class GenericAppMsgNdp : public ::inet::FieldsChunk
{
  protected:
    int numPacketsToSend = 0;
    bool isSender_ = false;
    bool isReceiver_ = false;
    bool isLongFlow_ = false;
    bool serverClose = false;
    uint32_t sequenceNumber = 0;

  private:
    void copy(const GenericAppMsgNdp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericAppMsgNdp&);

  public:
    GenericAppMsgNdp();
    GenericAppMsgNdp(const GenericAppMsgNdp& other);
    virtual ~GenericAppMsgNdp();
    GenericAppMsgNdp& operator=(const GenericAppMsgNdp& other);
    virtual GenericAppMsgNdp *dup() const override {return new GenericAppMsgNdp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNumPacketsToSend() const;
    virtual void setNumPacketsToSend(int numPacketsToSend);
    virtual bool isSender() const;
    virtual void setIsSender(bool isSender);
    virtual bool isReceiver() const;
    virtual void setIsReceiver(bool isReceiver);
    virtual bool isLongFlow() const;
    virtual void setIsLongFlow(bool isLongFlow);
    virtual bool getServerClose() const;
    virtual void setServerClose(bool serverClose);
    virtual uint32_t getSequenceNumber() const;
    virtual void setSequenceNumber(uint32_t sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GenericAppMsgNdp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GenericAppMsgNdp& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_GENERICAPPMSGNDP_M_H

