//
// Generated file, do not edit! Created by nedtool 5.6 from transportlayer/Ndp/NDPConnection.msg.
//

#ifndef __INET__NDP_NDPCONNECTION_M_H
#define __INET__NDP_NDPCONNECTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {
namespace ndp {

} // namespace ndp
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/ChunkBuffer_m.h" // import inet.common.packet.ChunkBuffer

#include "inet/common/packet/ChunkQueue_m.h" // import inet.common.packet.ChunkQueue

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address

// cplusplus {{
#include "Ndp.h"
#include "NDPAlgorithm.h"
#include "NDPConnection.h"
#include "NDPReceiveQueue.h"
#include "NDPSendQueue.h"
#include "ndp_common/NdpHeader.h"
// }}


namespace inet {
namespace ndp {

} // namespace ndp
} // namespace inet

#endif // ifndef __INET__NDP_NDPCONNECTION_M_H

